### ISSUE TITLE
Notes on latest tailscale (1.68.2)

### ISSUE THREAD

**Issue by BeautyyuYanli** [kaaanata/derper-docker#19]
Seems that the latest version of tailscale/derp relays on STUN for latency detection, so:
- STUN must be enabled
- network_mode should be set to "host"

I'm using Aliyun ECS (99/year) to run derp, and I've been struggling with this problem for several weeks :(

If more people run into the same issue, I believe these notes should be add to readme.

**Comment by BeautyyuYanli** [comment]
The second note seems to be related to #5

**Comment by zsio** [comment]
Thank you very much. I had been struggling with this issue until I saw your post. I put it behind a Caddy reverse proxy. Here are my CaddyFile and docker-compose.yaml configurations for anyone who might encounter the same problem.
非常感谢你，我之前遇到了这个问题一直没得到解决，直到看到你的帖子。我是放到了 Caddy 的反向代理后面的，这是我使用的 CaddyFile 和 docker-compose.yaml 配置，供遇到相同问题的人参考。

```
name: derper
services:
  derper:
    image: fredliang/derper
    restart: always
    network_mode: "host"
    environment:
      - DERP_DOMAIN=xxx.xxx.com
      - DERP_HTTP_PORT=10080
      - DERP_ADDR=0.0.0.0:10443
      - DERP_STUN=true
      - DERP_STUN_PORT=3478
      - DERP_VERIFY_CLIENTS=true
    volumes:
      - /var/run/tailscale/tailscaled.sock:/var/run/tailscale/tailscaled.sock
```

```
xxx.xxx.com {
	reverse_proxy https://127.0.0.1:10443 {
		transport http {
			tls_insecure_skip_verify
		}
	}
}
```
Additionally, make sure to open the DERP_STUN_PORT.
Please note that in my case, DERP_ADDR needs to be set in the format 0.0.0.0:PORT, otherwise it will report errors.
另外，请确保开放 DERP_STUN_PORT 端口号。
需要注意的是，在我的使用中，DERP_ADDR 需要设置为 0.0.0.0:PORT 的形式，否则会报错。
